sudo: required
dist: trusty

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sbt
    - $HOME/.ivy2

language: scala
scala:
  - 2.12.3
script:
  - sbt ++$TRAVIS_SCALA_VERSION compile test:compile &> compile.log
  - sbt ++$TRAVIS_SCALA_VERSION test > test.log
