sudo: required
dist: trusty

language: scala

jdk:
  - oraclejdk8
scala:
  - 2.11.8

before_script: # the automated download fails sometimes
    - export PATH=~/bin/amm:$PATH
    - mkdir -p ~/bin
    - if [ ! -f ~/bin/amm ]; then curl -L -o ~/bin/amm https://github.com/lihaoyi/Ammonite/releases/download/1.0.0/2.11-1.0.0 && chmod +x ~/bin/amm; fi
    - scripts/install_mesos.sh

script:
  - amm ci/pipeline travis

# Inspired by https://github.com/lihaoyi/Ammonite/blob/master/.travis.yml
cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.coursier

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
